baseURL = "/"
languageCode = "en-us"
title = "Mod Mappings"
theme = "beautifulhugo"
pygmentsCodefences  = true
pygmentsUseClasses  = true
rssLimit = 10  # Maximum number of items in the RSS feed.

  [[params.social]]
    name = "github"
    url = "https://github.com/ModMappings"

  [[params.social]]
    name = "twitter"
    url = "https://twitter.com/modmappings"

  [[params.social]]
    name = "discord"
    url = "https://discord.gg/KJR9nte"


[menu]
  [[menu.main]]
    name = "Posts"
    url = "posts/"
    weight = 10

  [[menu.main]]
    name = "Goals"
    url = "goals/"
    weight = 15

  [[menu.main]]
    name = "About"
    url = "about/"
    weight = 20

  [[menu.main]]
    name = "Contributors"
    url = "contributors/"
    weight = 25