baseURL = "/"
languageCode = "en-us"
title = "Mod Mappings"
theme = "cupper-hugo-theme"
[params]
    description = "Welcome to the mod mappings site"
    homeMetaContent = "Mod Mappings"
    darkThemeAsDefault = true


[[menu.nav]]
    name = "Home"
    url = "/"
    weight = 1

[[menu.nav]]
    name = "Posts"
    url = "/posts"
    weight = 2

[[menu.nav]]
    name = "About"
    url = "/about"
    weight = 3

[[menu.nav]]
    name = "Contributors"
    url = "/contributors"
    weight = 4

