baseURL = "/"
languageCode = "en-us"
title = "Mod Mappings"
description = "Mod Mappings"
theme = "docsy"

# Highlighting config
pygmentsCodeFences = true
pygmentsUseClasses = false
# Use the new Chroma Go highlighter in Hugo.
pygmentsUseClassic = false
#pygmentsOptions = "linenos=table"
# See https://help.farbox.com/pygments.html
pygmentsStyle = "tango"

## Configuration for BlackFriday markdown parser: https://github.com/russross/blackfriday
[blackfriday]
plainIDAnchors = true
hrefTargetBlank = true
angledQuotes = false
latexDashes = true

[params]
copyright = "Mod Mappings CC4"

# First one is picked as the Twitter card image if not set on page.
# images = ["images/project-illustration.png"]

# Menu title if your navbar has a versions selector to access old versions of your site.
# This menu appears only if you have at least one [params.versions] set.

# Enable Algolia DocSearch
algolia_docsearch = false

# Enable Lunr.js offline search
offlineSearch = false

[params.ui]
# Enable to show the side bar menu in its compact state.
sidebar_menu_compact = false
#  Set to true to disable breadcrumb navigation.
breadcrumb_disable = false
#  Set to true to hide the sidebar search box (the top nav search box will still be displayed if search is enabled)
sidebar_search_disable = true
#  Set to false if you don't want to display a logo (/assets/icons/logo.svg) in the top nav bar
navbar_logo = true
# Set to true to disable the About link in the site footer
footer_about_disable = false

[params.links]

[[params.links.user]]
	name = "Github"
	url = "https://github.com/ModMMappings"
	icon = "fa fa-github"
        desc = "Github"
[[params.links.user]]
	name ="Twitter"
	url = "https://twitter.com/modmappings"
	icon = "fab fa-twitter"
        desc = "Twitter"
[[params.links.user]]
	name = "Discord"
	url = "https://example.org/stack"
	icon = "fab fa-discord"
        desc = "Discord"

